version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: sreekanthlakka/blogapp-backend:latest
        container_name: backend
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=production
        restart: always

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: sreekanthlakka/blogapp-frontend:latest
        container_name: frontend
        ports:
            - "80:5173"
        depends_on:
            - backend
        restart: always
