name: deploy-app
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd backend && docker build -t sreekanthlakka/blogapp-backend .
            - run: cd frontend && docker build -t sreekanthlakka/blogapp-frontend .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push sreekanthlakka/blogapp-backend
            - run: docker push sreekanthlakka/blogapp-frontend

            - name: Add EC2 to known hosts
              run: |
                  ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}  # Ensure this is the correct private key
                  script: |
                      sudo apt-get update
                      sudo apt-get install -y docker.io
                      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                      sudo chmod +x /usr/local/bin/docker-compose
                      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                      cd /app
                      docker-compose pull
                      docker-compose up -d
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
