name: deploy-app
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd backend && docker build -t sreekanthlakka/blogapp-backend .
            - run: cd frontend && docker build -t sreekanthlakka/blogapp-frontend .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push sreekanthlakka/blogapp-backend
            - run: docker push sreekanthlakka/blogapp-frontend

            - name: Setup SSH
              run: |
                mkdir -p ~/.ssh
                touch ~/.ssh/known_hosts
                ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}  
                  script: |
                     sudo apt-get update
                      sudo apt-get install -y docker.io
                      
                      # Install Docker Compose if not installed
                      if [ ! -f /usr/local/bin/docker-compose ]; then
                        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                        sudo chmod +x /usr/local/bin/docker-compose
                      fi
                      
                      # Add ubuntu user to docker group
                      if ! groups ubuntu | grep &>/dev/null '\bdocker\b'; then
                        sudo usermod -aG docker ubuntu
                        newgrp docker
                      fi

                      # Clone the repo if it doesn't exist
                      if [ ! -d "/home/ubuntu/blogapp" ]; then
                        git clone https://github.com/shreekanthlakka/blogApp /home/ubuntu/blogapp
                      fi

                      cd /home/ubuntu/blogapp
                      
                      - name: Login to Docker Hub
                        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

                      # Pull latest images and run containers
                      sudo docker-compose pull
                      sudo docker-compose up -d
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                 
