name: deploy-app
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd backend && docker build -t sreekanthlakka/blogapp-backend .
            - run: cd frontend && docker build -t sreekanthlakka/blogapp-frontend .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push sreekanthlakka/blogapp-backend
            - run: docker push sreekanthlakka/blogapp-frontend
            - name: deploy to ec2
              uses: appleboy/ssh-action@master
              with: 
                host: ${{secrets.EC2_HOST}}
                username: ubuntu
                key: ${{secrets.EC2_SSH_KEY}}
                script: |
                   sudo docker pull sreekanthlakka/blogapp-backend:latest
                   sudo docker pull sreekanthlakka/blogapp-frontend:latest
                   sudo docker stop blogapp-backend || true
                   sudo docker stop blogapp-frontend || true
                   docker rmi $(docker image ls -q)
                   sudo docker run -d --name blogapp-backend -e APP_PORT 5000 -p 5000:5000 sreekanthlakka/blogapp-backend:latest
                   sudo docker run -d --name blogapp-frontend -p 5173:5173 sreekanthlakka/blogapp-frontend:latest
